### ISSUE TITLE
/ works differently from /index.html

### ISSUE THREAD

**Issue by Janiczek** [jhrcek/grbr#11]
http://localhost:3000/index.html is probably the URL intended to work with this tool
but if you go straight to http://localhost:3000/, you get a different view (without the menu at top etc.)

It should probably show the same thing as /index.html?

**Comment by jhrcek** [comment]
Agree, I'll fix that

**Comment by Janiczek** [comment]
also note that this `/` screen was more useful to me than the index - it showed the packages underneath the module names

**Comment by jhrcek** [comment]
The fix will be to remove the index.html path completely and make the root path behave like current index.html (= there will always be menu at the top). Regarding your 2nd comment that's what's controlled by the "clustering" checkbox in the menu.
- When it's checked, all nodes are grouped by package in large boxes and the component name in at the top of the grouping box
- When it's unchecked, the nodes are not grouped and the package name is present in each module's box

Does it mean that you'd prefer that you find non-clustered view more useful (= I should make it default?)

**Comment by jhrcek** [comment]
@Janiczek Should be fixed on master. Explicit `/index.html` route was removed and `/` now behaves as `/index.html` behaved previously. To get the more "useful" view try switching the "clustering" checkbox.

**Comment by jhrcek** [comment]
To explain: / used to be internal api for serving raw svg images which elm frontend controls by supplying various parameters. It was stupid to put it at the root, making it too easy for user to accidentally open the root url in the browser. The app should always be interacted with via the index page which is why I made the / serve index.html and moved the "internal" image route to other route to avoid it being used accidentally.

**Comment by jhrcek** [comment]
Accidentally closed, reopening to wait for confirmation :)

**Comment by Janiczek** [comment]
Please don't change any defaults wrt. the clustering :) I was a bit disoriented opening it for the second time ever :sweat_smile:

Thx for the tool again!

BTW it doesn't zoom well in Firefox, so I have to use Chrome. Is that issue known?

**Comment by jhrcek** [comment]
No, I didn't try it in firefox. I'll work on making it consistent in https://github.com/jhrcek/grbr/issues/12
Thanks for reporting the issue :)
